### ISSUE TITLE
利用create table select方式创建表出现core

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#18]
**利用create table select方式创建表出现core**
```
[mass2@localhost1 ~]$ psql -d postgres -p 4334
psql (PGXC 1.2devel, based on PG 9.3.13 ADB 2.2devel b3f7501)
Type "help" for help.

postgres=# create table tt(id integer,name char(10));
insert into tt values(1,'a');
insert into tt values(1,'b');
create table rr as select * from tt;
CREATE TABLE
postgres=# insert into tt values(1,'a');
INSERT 0 1
postgres=# insert into tt values(1,'b');
INSERT 0 1
postgres=# create table rr as select * from tt;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!>
```
**sql语句：**
```
create table tt(id integer,name char(10));
insert into tt values(1,'a');
insert into tt values(1,'b');
create table rr as select * from tt;
```
**core文件如下：**
```
(gdb) bt
#0  0x0000003991632495 in raise () from /lib64/libc.so.6
#1  0x0000003991633c75 in abort () from /lib64/libc.so.6
#2  0x0000000000996a6a in ExceptionalCondition (conditionName=0xb5d210 "!(conn->state != DN_CONNECTION_STATE_IDLE)", 
    errorType=0xb5ce09 "FailedAssertion", fileName=0xb5cd40 "/home/mass2/git/build/../AntDB/src/backend/pgxc/pool/execRemote.c", 
    lineNumber=1465) at /home/mass2/git/build/../AntDB/src/backend/utils/error/assert.c:54
#3  0x00000000006cc437 in handle_response (conn=0x2242e08, combiner=0x2294658)
    at /home/mass2/git/build/../AntDB/src/backend/pgxc/pool/execRemote.c:1465
#4  0x00000000006d0b5d in do_query (node=0x2294658) at /home/mass2/git/build/../AntDB/src/backend/pgxc/pool/execRemote.c:3694
#5  0x00000000006d0f24 in RemoteQueryNext (scan_node=0x2294658) at /home/mass2/git/build/../AntDB/src/backend/pgxc/pool/execRemote.c:3840
#6  0x00000000006807b0 in ExecScanFetch (node=0x2294658, accessMtd=0x6d0eb4 <RemoteQueryNext>, recheckMtd=0x6d0ea1 <RemoteQueryRecheck>)
    at /home/mass2/git/build/../AntDB/src/backend/executor/execScan.c:82
#7  0x0000000000680824 in ExecScan (node=0x2294658, accessMtd=0x6d0eb4 <RemoteQueryNext>, recheckMtd=0x6d0ea1 <RemoteQueryRecheck>)
    at /home/mass2/git/build/../AntDB/src/backend/executor/execScan.c:132
#8  0x00000000006d0e9f in ExecRemoteQuery (node=0x2294658) at /home/mass2/git/build/../AntDB/src/backend/pgxc/pool/execRemote.c:3792
#9  0x0000000000675444 in ExecProcNode (node=0x2294658) at /home/mass2/git/build/../AntDB/src/backend/executor/execProcnode.c:516
#10 0x000000000069a020 in ExecModifyTable (node=0x22944e0) at /home/mass2/git/build/../AntDB/src/backend/executor/nodeModifyTable.c:1110
#11 0x00000000006751fe in ExecProcNode (node=0x22944e0) at /home/mass2/git/build/../AntDB/src/backend/executor/execProcnode.c:388
#12 0x0000000000672e10 in ExecutePlan (estate=0x22942f8, planstate=0x22944e0, operation=CMD_INSERT, sendTuples=0 '\000', numberTuples=0, 
    direction=ForwardScanDirection, dest=0x22a0110) at /home/mass2/git/build/../AntDB/src/backend/executor/execMain.c:1496
#13 0x0000000000670e5c in standard_ExecutorRun (queryDesc=0x22261f0, direction=ForwardScanDirection, count=0)
    at /home/mass2/git/build/../AntDB/src/backend/executor/execMain.c:321
#14 0x0000000000670cc2 in ExecutorRun (queryDesc=0x22261f0, direction=ForwardScanDirection, count=0)
    at /home/mass2/git/build/../AntDB/src/backend/executor/execMain.c:269
---Type <return> to continue, or q <return> to quit---   
#15 0x000000000086ae99 in ProcessQuery (plan=0x22a0018, sourceText=0x21497f8 "create table rr as select * from tt;", params=0x0, 
    dest=0x22a0110, completionTag=0x7ffe172b7580 "") at /home/mass2/git/build/../AntDB/src/backend/tcop/pquery.c:191
#16 0x000000000086c9a0 in PortalRunMulti (portal=0x214ea58, isTopLevel=1 '\001', dest=0x22a0110, altdest=0x22a0110, 
    completionTag=0x7ffe172b7580 "") at /home/mass2/git/build/../AntDB/src/backend/tcop/pquery.c:1382
#17 0x000000000086be9d in PortalRun (portal=0x214ea58, count=9223372036854775807, isTopLevel=1 '\001', dest=0x22a0110, 
    altdest=0x22a0110, completionTag=0x7ffe172b7580 "") at /home/mass2/git/build/../AntDB/src/backend/tcop/pquery.c:878
#18 0x0000000000864e4e in exec_simple_query (query_string=0x21488b8 "create table rr as select * from tt;", query_node=0x0)
    at /home/mass2/git/build/../AntDB/src/backend/tcop/postgres.c:1468
#19 0x0000000000869b57 in PostgresMain (argc=1, argv=0x21302a8, dbname=0x2130108 "postgres", username=0x21300e8 "mass2")
    at /home/mass2/git/build/../AntDB/src/backend/tcop/postgres.c:4884
#20 0x00000000007fd539 in BackendRun (port=0x2153880) at /home/mass2/git/build/../AntDB/src/backend/postmaster/postmaster.c:4577
#21 0x00000000007fcc58 in BackendStartup (port=0x2153880) at /home/mass2/git/build/../AntDB/src/backend/postmaster/postmaster.c:4240
#22 0x00000000007f905b in ServerLoop () at /home/mass2/git/build/../AntDB/src/backend/postmaster/postmaster.c:1858
#23 0x00000000007f87ca in PostmasterMain (argc=5, argv=0x212e260)
    at /home/mass2/git/build/../AntDB/src/backend/postmaster/postmaster.c:1482
#24 0x00000000006e79b5 in main (argc=5, argv=0x212e260) at /home/mass2/git/build/../AntDB/src/backend/main/main.c:234
```

**Comment by mass3** [comment]
当前未发现问题
```
postgres=# create table tt(id integer,name char(10));
insert into tt values(1,'a');
insert into tt values(1,'b');
create table rr as select * from tt;
CREATE TABLE
postgres=# insert into tt values(1,'a');
INSERT 0 1
postgres=# insert into tt values(1,'b');
INSERT 0 1
postgres=# create table rr as select * from tt;
INSERT 0 2
postgres=#
```
