### ISSUE TITLE
打开enable_cluster_plan，一定条件下join操作出现core

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#29]
postgres=# \c cidb
You are now connected to database "cidb" as user "mass2".
cidb=# explain (costs off)
cidb-# select * from
cidb-#   (select 1 as id) as xx
cidb-#   left join
cidb-#     (tenk1 as a1 full join (select 1 as id) as yy on (a1.unique1 = yy.id))
cidb-#   on (xx.id = coalesce(yy.id));
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
**core文件内容：单独跑没有复现，跑regress有core**
```
(gdb) bt
#0  0x0000003991632495 in raise () from /lib64/libc.so.6
#1  0x0000003991633c75 in abort () from /lib64/libc.so.6
#2  0x0000000000abd5ee in ExceptionalCondition (conditionName=0xca2958 "!((eflags & (0x0002 | 0x0004 | 0x0008)) == 0)", 
    errorType=0xca28e6 "FailedAssertion", fileName=0xca2820 "/home/mass2/git/build/../AntDB/src/backend/executor/nodeClusterReduce.c", 
    lineNumber=104) at /home/mass2/git/build/../AntDB/src/backend/utils/error/assert.c:54
#3  0x000000000071977e in ExecInitClusterReduce (node=0x2de37a8, estate=0x2e00f38, eflags=19)
    at /home/mass2/git/build/../AntDB/src/backend/executor/nodeClusterReduce.c:104
#4  0x00000000006cfbac in ExecInitNode (node=0x2de37a8, estate=0x2e00f38, eflags=19)
    at /home/mass2/git/build/../AntDB/src/backend/executor/execProcnode.c:373
#5  0x00000000006f8439 in ExecInitMergeJoin (node=0x2deb008, estate=0x2e00f38, eflags=19)
    at /home/mass2/git/build/../AntDB/src/backend/executor/nodeMergejoin.c:1525
#6  0x00000000006cf97e in ExecInitNode (node=0x2deb008, estate=0x2e00f38, eflags=19)
    at /home/mass2/git/build/../AntDB/src/backend/executor/execProcnode.c:279
#7  0x00000000006fcede in ExecInitNestLoop (node=0x2deaf38, estate=0x2e00f38, eflags=19)
    at /home/mass2/git/build/../AntDB/src/backend/executor/nodeNestloop.c:348
#8  0x00000000006cf95f in ExecInitNode (node=0x2deaf38, estate=0x2e00f38, eflags=17)
    at /home/mass2/git/build/../AntDB/src/backend/executor/execProcnode.c:274
#9  0x0000000000715fb3 in ExecStartClusterPlan (plan=0x2deaf38, estate=0x2e00f38, eflags=17, rnodes=0x2de8338)
    at /home/mass2/git/build/../AntDB/src/backend/executor/execCluster.c:315
#10 0x000000000071506e in ExecInitClusterGather (node=0x2de4bc0, estate=0x2e00f38, flags=17)
    at /home/mass2/git/build/../AntDB/src/backend/executor/nodeClusterGather.c:40
#11 0x00000000006cfb4f in ExecInitNode (node=0x2de4bc0, estate=0x2e00f38, eflags=17)
    at /home/mass2/git/build/../AntDB/src/backend/executor/execProcnode.c:358
#12 0x00000000006caca9 in InitPlan (queryDesc=0x2dffcc8, eflags=17) at /home/mass2/git/build/../AntDB/src/backend/executor/execMain.c:995
---Type <return> to continue, or q <return> to quit---  
#13 0x00000000006c9aeb in standard_ExecutorStart (queryDesc=0x2dffcc8, eflags=17)
    at /home/mass2/git/build/../AntDB/src/backend/executor/execMain.c:249
#14 0x00000000006c98ca in ExecutorStart (queryDesc=0x2dffcc8, eflags=1)
    at /home/mass2/git/build/../AntDB/src/backend/executor/execMain.c:151
#15 0x0000000000651ad2 in ExplainOnePlan (plannedstmt=0x2dffc30, into=0x0, es=0x2dd6c18, 
    queryString=0x2d36e18 "explain (costs off)\nselect * from\n  (select 1 as id) as xx\n  left join\n    (tenk1 as a1 full join (select 1 as id) as yy on (a1.unique1 = yy.id))\n  on (xx.id = coalesce(yy.id));", params=0x0, planduration=0x7ffe9bc87ea0)
    at /home/mass2/git/build/../AntDB/src/backend/commands/explain.c:522
#16 0x00000000006517f5 in ExplainOneQuery (query=0x2dd6ce8, into=0x0, es=0x2dd6c18, 
    queryString=0x2d36e18 "explain (costs off)\nselect * from\n  (select 1 as id) as xx\n  left join\n    (tenk1 as a1 full join (select 1 as id) as yy on (a1.unique1 = yy.id))\n  on (xx.id = coalesce(yy.id));", params=0x0)
    at /home/mass2/git/build/../AntDB/src/backend/commands/explain.c:390
#17 0x0000000000651468 in ExplainQuery (stmt=0x2d36d80, 
    queryString=0x2d36e18 "explain (costs off)\nselect * from\n  (select 1 as id) as xx\n  left join\n    (tenk1 as a1 full join (select 1 as id) as yy on (a1.unique1 = yy.id))\n  on (xx.id = coalesce(yy.id));", params=0x0, dest=0x2dd6b80)
    at /home/mass2/git/build/../AntDB/src/backend/commands/explain.c:275
#18 0x000000000095ed42 in standard_ProcessUtility (parsetree=0x2d36d80, 
    queryString=0x2d36e18 "explain (costs off)\nselect * from\n  (select 1 as id) as xx\n  left join\n    (tenk1 as a1 full join (select 1 as id) as yy on (a1.unique1 = yy.id))\n  on (xx.id = coalesce(yy.id));", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, dest=0x2dd6b80, 
    sentToRemote=0 '\000', completionTag=0x7ffe9bc88280 "") at /home/mass2/git/build/../AntDB/src/backend/tcop/utility.c:923
#19 0x000000000095de85 in ProcessUtility (parsetree=0x2d36d80, 
    queryString=0x2d36e18 "explain (costs off)\nselect * from\n  (select 1 as id) as xx\n  left join\n    (tenk1 as a1 full join (select 1 as id) as yy on (a1.unique1 = yy.id))\n  on (xx.id = coalesce(yy.id));", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, dest=0x2dd6b80, 
    sentToRemote=0 '\000', completionTag=0x7ffe9bc88280 "") at /home/mass2/git/build/../AntDB/src/backend/tcop/utility.c:402
---Type <return> to continue, or q <return> to quit---
#20 0x000000000095cd87 in PortalRunUtility (portal=0x2d9da98, utilityStmt=0x2d36d80, isTopLevel=1 '\001', setHoldSnapshot=1 '\001', 
    dest=0x2dd6b80, completionTag=0x7ffe9bc88280 "") at /home/mass2/git/build/../AntDB/src/backend/tcop/pquery.c:1289
#21 0x000000000095ca44 in FillPortalStore (portal=0x2d9da98, isTopLevel=1 '\001')
    at /home/mass2/git/build/../AntDB/src/backend/tcop/pquery.c:1144
#22 0x000000000095c2f5 in PortalRun (portal=0x2d9da98, count=9223372036854775807, isTopLevel=1 '\001', dest=0x2dd1e48, 
    altdest=0x2dd1e48, completionTag=0x7ffe9bc88470 "") at /home/mass2/git/build/../AntDB/src/backend/tcop/pquery.c:850
#23 0x000000000095599d in exec_simple_query (
    query_string=0x2d35018 "explain (costs off)\nselect * from\n  (select 1 as id) as xx\n  left join\n    (tenk1 as a1 full join (select 1 as id) as yy on (a1.unique1 = yy.id))\n  on (xx.id = coalesce(yy.id));", query_node=0x0)
    at /home/mass2/git/build/../AntDB/src/backend/tcop/postgres.c:1499
#24 0x000000000095a0dd in PostgresMain (argc=1, argv=0x2cd28f8, dbname=0x2cd2760 "cidb", username=0x2cd2740 "mass2")
    at /home/mass2/git/build/../AntDB/src/backend/tcop/postgres.c:4773
#25 0x00000000008c3c68 in BackendRun (port=0x2cce160) at /home/mass2/git/build/../AntDB/src/backend/postmaster/postmaster.c:4634
#26 0x00000000008c33d3 in BackendStartup (port=0x2cce160) at /home/mass2/git/build/../AntDB/src/backend/postmaster/postmaster.c:4308
#27 0x00000000008bf5c3 in ServerLoop () at /home/mass2/git/build/../AntDB/src/backend/postmaster/postmaster.c:1848
#28 0x00000000008bec71 in PostmasterMain (argc=5, argv=0x2ca6230)
    at /home/mass2/git/build/../AntDB/src/backend/postmaster/postmaster.c:1456
#29 0x0000000000756486 in main (argc=5, argv=0x2ca6230) at /home/mass2/git/build/../AntDB/src/backend/main/main.c:228
(gdb) 

```
测试sql：
```
psql -d postgres -p 4334
\c cidb
explain (costs off)
select * from
  (select 1 as id) as xx
  left join
    (tenk1 as a1 full join (select 1 as id) as yy on (a1.unique1 = yy.id))
  on (xx.id = coalesce(yy.id));

```

**Comment by mass3** [comment]
问题已经解决
cidb=# explain (costs off)
cidb-# select * from
cidb-#   (select 1 as id) as xx
cidb-#   left join
cidb-#     (tenk1 as a1 full join (select 1 as id) as yy on (a1.unique1 = yy.id))
cidb-#   on (xx.id = coalesce(yy.id));
                             QUERY PLAN                             
--------------------------------------------------------------------
 Cluster Gather
   ->  Nested Loop Left Join
         Join Filter: ((1) = COALESCE((1)))
         ->  Result
         ->  Merge Full Join
               Merge Cond: (a1.unique1 = (1))
               ->  Cluster Merge Reduce
                     Sort Key: a1.unique1
                     ->  Index Scan using tenk1_unique1 on tenk1 a1
               ->  Sort
                     Sort Key: (1)
                     ->  Result
(12 rows)

cidb=#
