### ISSUE TITLE
执行cluster，出现core

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#45]
### 执行cluster，出现core
```
postgres=# \d
No relations found.
postgres=# cluster;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> \q
```

### core文件内容：
```
(gdb) bt
#0  0x0000000000578cc6 in RangeVarGetRelidExtended (relation=0x0, lockmode=0, missing_ok=0 '\000', nowait=0 '\000', callback=0, 
    callback_arg=0x0) at /home/mass2/git/build/../adb_sql/src/backend/catalog/namespace.c:248
#1  0x00000000004d3bcd in relation_openrv (relation=0x0, lockmode=0)
    at /home/mass2/git/build/../adb_sql/src/backend/access/heap/heapam.c:1216
#2  0x000000000095f04a in standard_ProcessUtility (parsetree=0x2468540, queryString=0x24685d8 "cluster;", 
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, dest=0x2468978, sentToRemote=0 '\000', completionTag=0x7fff25d4d3a0 "")
    at /home/mass2/git/build/../adb_sql/src/backend/tcop/utility.c:882
#3  0x000000000095e2ad in ProcessUtility (parsetree=0x2468540, queryString=0x24685d8 "cluster;", context=PROCESS_UTILITY_TOPLEVEL, 
    params=0x0, dest=0x2468978, sentToRemote=0 '\000', completionTag=0x7fff25d4d3a0 "")
    at /home/mass2/git/build/../adb_sql/src/backend/tcop/utility.c:402
#4  0x000000000095d1af in PortalRunUtility (portal=0x2508828, utilityStmt=0x2468540, isTopLevel=1 '\001', setHoldSnapshot=0 '\000', 
    dest=0x2468978, completionTag=0x7fff25d4d3a0 "") at /home/mass2/git/build/../adb_sql/src/backend/tcop/pquery.c:1289
#5  0x000000000095d46f in PortalRunMulti (portal=0x2508828, isTopLevel=1 '\001', setHoldSnapshot=0 '\000', dest=0x2468978, 
    altdest=0x2468978, completionTag=0x7fff25d4d3a0 "") at /home/mass2/git/build/../adb_sql/src/backend/tcop/pquery.c:1454
#6  0x000000000095c819 in PortalRun (portal=0x2508828, count=9223372036854775807, isTopLevel=1 '\001', dest=0x2468978, 
    altdest=0x2468978, completionTag=0x7fff25d4d3a0 "") at /home/mass2/git/build/../adb_sql/src/backend/tcop/pquery.c:881
#7  0x0000000000955dbd in exec_simple_query (query_string=0x2467b58 "cluster;", query_node=0x0)
    at /home/mass2/git/build/../adb_sql/src/backend/tcop/postgres.c:1500
#8  0x000000000095a502 in PostgresMain (argc=1, argv=0x2408d28, dbname=0x2408b88 "postgres", username=0x2408b68 "mass2")
    at /home/mass2/git/build/../adb_sql/src/backend/tcop/postgres.c:4780
---Type <return> to continue, or q <return> to quit---  
#9  0x00000000008c4088 in BackendRun (port=0x2404160) at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:4634
#10 0x00000000008c37f3 in BackendStartup (port=0x2404160) at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:4308
#11 0x00000000008bf9e3 in ServerLoop () at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:1848
#12 0x00000000008bf091 in PostmasterMain (argc=5, argv=0x23dc230)
    at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:1456
#13 0x0000000000756292 in main (argc=5, argv=0x23dc230) at /home/mass2/git/build/../adb_sql/src/backend/main/main.c:228
(gdb) 
```

**Comment by constzl** [comment]
commit 97e571852164c098e07a3514358634454419dccd
Author: zhangliang10 <zhangliang10@asiainfo.com>
Date:   Thu Dec 14 17:13:47 2017 +0800

    修正 #45: 执行cluster，出现core
    
    缺少必要的参数校验

**Comment by mass3** [comment]
cluster命令功能正常
```
postgres=# cluster;
CLUSTER
postgres=# 
```
