### ISSUE TITLE
跑regress出现，打开enable_cluster_plan，delete触发rule，出现core

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#47]
单独跑sql没有复现，跑regress出现，需要复现请联系本人
```
postgres=# \c cidb;
You are now connected to database "cidb" as user "mass2".
cidb=# delete from rtest_v1 where b = 12;
ERROR:  server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```
core文件：
```
(gdb) bt
#0  0x0000003991632495 in raise () from /lib64/libc.so.6
#1  0x0000003991633c75 in abort () from /lib64/libc.so.6
#2  0x0000000000abdbfe in ExceptionalCondition (conditionName=0xb4a9a4 "!(((lp)->lp_flags == 1))", errorType=0xb4725e "FailedAssertion", 
    fileName=0xb472e8 "/home/mass2/git/build/../adb_sql/src/backend/access/heap/heapam.c", lineNumber=3064)
    at /home/mass2/git/build/../adb_sql/src/backend/utils/error/assert.c:54
#3  0x00000000004d7602 in heap_delete (relation=0x7f8020266380, tid=0x7ffc2b3b9ed0, cid=0, crosscheck=0x0, wait=1 '\001', 
    hufd=0x7ffc2b3b9e00) at /home/mass2/git/build/../adb_sql/src/backend/access/heap/heapam.c:3064
#4  0x00000000006f98a5 in ExecDelete (tupleid=0x7ffc2b3b9ed0, oldtuple=0x0, planSlot=0x1535b38, epqstate=0x1508f60, estate=0x15089e8, 
    canSetTag=1 '\001', pslot=0x1535b38) at /home/mass2/git/build/../adb_sql/src/backend/executor/nodeModifyTable.c:741
#5  0x00000000006fb3d7 in ExecModifyTable (node=0x1508e98)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/nodeModifyTable.c:1765
#6  0x00000000006cfd34 in ExecProcNode (node=0x1508e98) at /home/mass2/git/build/../adb_sql/src/backend/executor/execProcnode.c:445
#7  0x00000000006cbe3d in ExecutePlan (estate=0x15089e8, planstate=0x1508e98, use_parallel_mode=0 '\000', operation=CMD_SELECT, 
    sendTuples=1 '\001', numberTuples=0, direction=ForwardScanDirection, dest=0x1462b78)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execMain.c:1624
#8  0x00000000006c9c95 in standard_ExecutorRun (queryDesc=0x150d590, direction=ForwardScanDirection, count=0)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execMain.c:352
#9  0x00000000006c9af4 in ExecutorRun (queryDesc=0x150d590, direction=ForwardScanDirection, count=0)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execMain.c:297
#10 0x0000000000715792 in exec_cluster_plan (splan=0x14d0588, length=3984)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execCluster.c:145
#11 0x000000000095ae2d in PostgresMain (argc=1, argv=0x14727d8, dbname=0x1472710 "cidb", username=0x14726f0 "mass2")
    at /home/mass2/git/build/../adb_sql/src/backend/tcop/postgres.c:5120
#12 0x00000000008c41c4 in BackendRun (port=0x1466d70) at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:4634
---Type <return> to continue, or q <return> to quit--- 
#13 0x00000000008c392f in BackendStartup (port=0x1466d70) at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:4308
#14 0x00000000008bfb1f in ServerLoop () at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:1848
#15 0x00000000008bf1cd in PostmasterMain (argc=5, argv=0x1443230)
    at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:1456
#16 0x00000000007563ce in main (argc=5, argv=0x1443230) at /home/mass2/git/build/../adb_sql/src/backend/main/main.c:228
(gdb) 
```

**Comment by mass3** [comment]
打开开关，多次跑regress，未出现core。
