### ISSUE TITLE
表中有array类型的列，查询出现core

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#56]
表中有array类型的列，查询出现core
```
postgres=# select * from inserttest;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```
测试sql：
```
create type insert_test_type as (if1 int, if2 text[]);
create table inserttest (f1 int, f2 int[],
                         f3 insert_test_type, f4 insert_test_type[]);
insert into inserttest (f2[1], f2[2]) values (1,2);
insert into inserttest (f2[1], f2[2]) values (3,4), (5,6);
insert into inserttest (f2[1], f2[2]) select 7,8;
insert into inserttest (f3.if1, f3.if2) values (1,array['foo']);
insert into inserttest (f3.if1, f3.if2) values (1,'{foo}'), (2,'{bar}');
insert into inserttest (f3.if1, f3.if2) select 3, '{baz,quux}';
insert into inserttest (f3.if2[1], f3.if2[2]) values ('foo', 'bar');
insert into inserttest (f3.if2[1], f3.if2[2]) values ('foo', 'bar'), ('baz', 'quux');
insert into inserttest (f3.if2[1], f3.if2[2]) select 'bear', 'beer';
insert into inserttest (f4[1].if2[1], f4[1].if2[2]) values ('foo', 'bar');
insert into inserttest (f4[1].if2[1], f4[1].if2[2]) values ('foo', 'bar'), ('baz', 'quux');
insert into inserttest (f4[1].if2[1], f4[1].if2[2]) select 'bear', 'beer';
select * from inserttest;
```
core文件：
```
(gdb) bt
#0  0x0000003991632495 in raise () from /lib64/libc.so.6
#1  0x0000003991633c75 in abort () from /lib64/libc.so.6
#2  0x0000000000abcc32 in ExceptionalCondition (
    conditionName=0xd4fcd0 "!(pointer == (void *) (((uintptr_t) ((pointer)) + ((8) - 1)) & ~((uintptr_t) ((8) - 1))))", 
    errorType=0xd4fbb5 "FailedAssertion", fileName=0xd4fac0 "/home/mass2/git/build/../adb_sql/src/backend/utils/mmgr/mcxt.c", 
    lineNumber=1006) at /home/mass2/git/build/../adb_sql/src/backend/utils/error/assert.c:54
#3  0x0000000000aef0f4 in pfree (pointer=0x1c6c7bc) at /home/mass2/git/build/../adb_sql/src/backend/utils/mmgr/mcxt.c:1006
#4  0x0000000000983bd0 in CopyArrayEls (array=0x1c6ca80, values=0x1c6cbe8, nulls=0x1c6cc08 "", nitems=1, typlen=-1, typbyval=0 '\000', 
    typalign=105 'i', freedata=1 '\001') at /home/mass2/git/build/../adb_sql/src/backend/utils/adt/arrayfuncs.c:1028
#5  0x00000000004965fb in convert_array_recv (fcinfo=0x7fffc399b670)
    at /home/mass2/git/build/../adb_sql/src/backend/access/common/tuptypeconvert.c:763
#6  0x0000000000ac98a6 in ReceiveFunctionCall (flinfo=0x1c6c350, buf=0x7fffc399bb30, typioparam=25, typmod=-1)
    at /home/mass2/git/build/../adb_sql/src/backend/utils/fmgr/fmgr.c:2015
#7  0x0000000000494638 in do_type_convert_slot_in (convert=0x1c6c698, src=0x1c6aae8, dest=0x1c6a9d0, need_copy=0 '\000')
    at /home/mass2/git/build/../adb_sql/src/backend/access/common/tuptypeconvert.c:147
#8  0x0000000000495c22 in convert_record_recv (fcinfo=0x7fffc399bc10)
    at /home/mass2/git/build/../adb_sql/src/backend/access/common/tuptypeconvert.c:563
#9  0x0000000000ac98a6 in ReceiveFunctionCall (flinfo=0x1c6b0e8, buf=0x7fffc399c0d0, typioparam=90114, typmod=-1)
    at /home/mass2/git/build/../adb_sql/src/backend/utils/fmgr/fmgr.c:2015
#10 0x0000000000494638 in do_type_convert_slot_in (convert=0x1c6ac98, src=0x1c52f58, dest=0x1c52dc0, need_copy=0 '\000')
    at /home/mass2/git/build/../adb_sql/src/backend/access/common/tuptypeconvert.c:147
#11 0x0000000000725945 in HandleCopyOutData (context=0x7fffc399c3e0, conn=0x1b79880, buf=0x1c59e8d "d\004", len=104)
    at /home/mass2/git/build/../adb_sql/src/backend/intercomm/inter-query.c:660
#12 0x0000000000725b7f in RemoteQueryFinishHook (context=0x7fffc399c3e0, conn=0x1b79880, type=PQNHFT_COPY_OUT_DATA)
    at /home/mass2/git/build/../adb_sql/src/backend/intercomm/inter-query.c:695
---Type <return> to continue, or q <return> to quit--- 
#13 0x000000000073ca9e in PQNExecFinish (conn=0x1b79880, hook=0x7259c0 <RemoteQueryFinishHook>, context=0x7fffc399c3e0)
    at /home/mass2/git/build/../adb_sql/src/backend/libpq/libpq-node.c:500
#14 0x000000000073c444 in PQNListExecFinish (conn_list=0x1c53a80, get_pgconn_hook=0x720103 <HandleGetPGconn>, 
    hook=0x7259c0 <RemoteQueryFinishHook>, context=0x7fffc399c3e0, blocking=1 '\001')
    at /home/mass2/git/build/../adb_sql/src/backend/libpq/libpq-node.c:344
#15 0x0000000000725181 in FetchRemoteQuery (node=0x1c51ec0, destslot=0x1c52810)
    at /home/mass2/git/build/../adb_sql/src/backend/intercomm/inter-query.c:486
#16 0x00000000007511fb in RemoteQueryNext (scan_node=0x1c51ec0)
    at /home/mass2/git/build/../adb_sql/src/backend/pgxc/pool/execRemote.c:472
#17 0x00000000006dd744 in ExecScanFetch (node=0x1c51ec0, accessMtd=0x7510ee <RemoteQueryNext>, recheckMtd=0x7510db <RemoteQueryRecheck>)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execScan.c:95
#18 0x00000000006dd7b8 in ExecScan (node=0x1c51ec0, accessMtd=0x7510ee <RemoteQueryNext>, recheckMtd=0x7510db <RemoteQueryRecheck>)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execScan.c:145
#19 0x00000000007510d9 in ExecRemoteQuery (node=0x1c51ec0) at /home/mass2/git/build/../adb_sql/src/backend/pgxc/pool/execRemote.c:401
#20 0x00000000006d1de0 in ExecProcNode (node=0x1c51ec0) at /home/mass2/git/build/../adb_sql/src/backend/executor/execProcnode.c:589
#21 0x00000000006cdc49 in ExecutePlan (estate=0x1c51da8, planstate=0x1c51ec0, use_parallel_mode=0 '\000', operation=CMD_SELECT, 
    sendTuples=1 '\001', numberTuples=0, direction=ForwardScanDirection, dest=0x1c4d558)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execMain.c:1624
#22 0x00000000006cbaa1 in standard_ExecutorRun (queryDesc=0x1b794a8, direction=ForwardScanDirection, count=0)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execMain.c:352
#23 0x00000000006cb900 in ExecutorRun (queryDesc=0x1b794a8, direction=ForwardScanDirection, count=0)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execMain.c:297
#24 0x000000000095bc68 in PortalRunSelect (portal=0x1c4fd98, forward=1 '\001', count=0, dest=0x1c4d558)
    at /home/mass2/git/build/../adb_sql/src/backend/tcop/pquery.c:1040
#25 0x000000000095b85b in PortalRun (portal=0x1c4fd98, count=9223372036854775807, isTopLevel=1 '\001', dest=0x1c4d558, 
---Type <return> to continue, or q <return> to quit---
    altdest=0x1c4d558, completionTag=0x7fffc399c890 "") at /home/mass2/git/build/../adb_sql/src/backend/tcop/pquery.c:855
#26 0x0000000000954ed9 in exec_simple_query (query_string=0x1bdbe98 "select * from inserttest;", query_node=0x0)
    at /home/mass2/git/build/../adb_sql/src/backend/tcop/postgres.c:1500
#27 0x000000000095961e in PostgresMain (argc=1, argv=0x1b809f0, dbname=0x1b80850 "postgres", username=0x1b80830 "mass2")
    at /home/mass2/git/build/../adb_sql/src/backend/tcop/postgres.c:4780
#28 0x00000000008c31a4 in BackendRun (port=0x1b784a0) at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:4634
#29 0x00000000008c290f in BackendStartup (port=0x1b784a0) at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:4308
#30 0x00000000008beaff in ServerLoop () at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:1848
#31 0x00000000008be1ad in PostmasterMain (argc=5, argv=0x1b505f0)
    at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:1456
#32 0x0000000000755506 in main (argc=5, argv=0x1b505f0) at /home/mass2/git/build/../adb_sql/src/backend/main/main.c:228
(gdb) 
```

**Comment by mass3** [comment]
The problem has been solved.
postgres=# select * from inserttest;
 f1 |  f2   |        f3        |           f4           
----+-------+------------------+------------------------
    | {1,2} |                  | 
    | {3,4} |                  | 
    | {5,6} |                  | 
    | {7,8} |                  | 
    |       | (1,{foo})        | 
    |       | (1,{foo})        | 
    |       | (2,{bar})        | 
    |       | (3,"{baz,quux}") | 
    |       | (,"{foo,bar}")   | 
    |       | (,"{foo,bar}")   | 
    |       | (,"{baz,quux}")  | 
    |       | (,"{bear,beer}") | 
    |       |                  | {"(,\"{foo,bar}\")"}
    |       |                  | {"(,\"{foo,bar}\")"}
    |       |                  | {"(,\"{baz,quux}\")"}
    |       |                  | {"(,\"{bear,beer}\")"}
(16 rows)
