### ISSUE TITLE
打开enable_cluster_plan，两个hash表join，出现core

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#60]
## 打开enable_cluster_plan，两个hash表join，出现core
```
postgres=# set enable_cluster_plan = on; 
SET
postgres=# select * from xc_sort1_hash join xc_sort2_hash using (val2) order by xc_sort1_hash.val, xc_sort2_hash.val, xc_sort2_hash.val2; 
ERROR:  server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

postgres=# 
```
### core文件：
```
(gdb) bt
#0  0x0000003991632495 in raise () from /lib64/libc.so.6
#1  0x0000003991633c75 in abort () from /lib64/libc.so.6
#2  0x0000000000abd11a in ExceptionalCondition (conditionName=0xca2c6d "!(0)", errorType=0xca2b8e "FailedAssertion", 
    fileName=0xca2ac0 "/home/mass2/git/build/../adb_sql/src/backend/executor/nodeClusterReduce.c", lineNumber=279)
    at /home/mass2/git/build/../adb_sql/src/backend/utils/error/assert.c:54
#3  0x000000000071bb3f in GetSlotFromOuter (node=0x1572268)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/nodeClusterReduce.c:279
#4  0x000000000071beb4 in ExecClusterReduce (node=0x1572268)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/nodeClusterReduce.c:424
#5  0x00000000006d1df1 in ExecProcNode (node=0x1572268) at /home/mass2/git/build/../adb_sql/src/backend/executor/execProcnode.c:605
#6  0x00000000006f0dc0 in ExecHashJoinOuterGetTuple (outerNode=0x1572268, hjstate=0x1571220, hashvalue=0x7fff01d33320)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/nodeHashjoin.c:672
#7  0x00000000006f018b in ExecHashJoin (node=0x1571220) at /home/mass2/git/build/../adb_sql/src/backend/executor/nodeHashjoin.c:217
#8  0x00000000006d1c8f in ExecProcNode (node=0x1571220) at /home/mass2/git/build/../adb_sql/src/backend/executor/execProcnode.c:533
#9  0x0000000000702b02 in ExecSort (node=0x1570e50) at /home/mass2/git/build/../adb_sql/src/backend/executor/nodeSort.c:103
#10 0x00000000006d1cb9 in ExecProcNode (node=0x1570e50) at /home/mass2/git/build/../adb_sql/src/backend/executor/execProcnode.c:544
#11 0x00000000006cdc09 in ExecutePlan (estate=0x1570d38, planstate=0x1570e50, use_parallel_mode=0 '\000', operation=CMD_SELECT, 
    sendTuples=1 '\001', numberTuples=0, direction=ForwardScanDirection, dest=0x14bae08)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execMain.c:1624
#12 0x00000000006cba61 in standard_ExecutorRun (queryDesc=0x157b7a8, direction=ForwardScanDirection, count=0)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execMain.c:352
#13 0x00000000006cb8c0 in ExecutorRun (queryDesc=0x157b7a8, direction=ForwardScanDirection, count=0)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execMain.c:297
#14 0x000000000071753a in exec_cluster_plan (splan=0x15284b0, length=3624)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execCluster.c:145
#15 0x000000000095a2f5 in PostgresMain (argc=1, argv=0x14cbf60, dbname=0x149d7c8 "postgres", username=0x14cbe60 "mass2")
---Type <return> to continue, or q <return> to quit---
    at /home/mass2/git/build/../adb_sql/src/backend/tcop/postgres.c:5120
#16 0x00000000008c368c in BackendRun (port=0x14bf0b0) at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:4634
#17 0x00000000008c2df7 in BackendStartup (port=0x14bf0b0) at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:4308
#18 0x00000000008befe7 in ServerLoop () at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:1848
#19 0x00000000008be695 in PostmasterMain (argc=5, argv=0x149b5f0)
    at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:1456
#20 0x0000000000755576 in main (argc=5, argv=0x149b5f0) at /home/mass2/git/build/../adb_sql/src/backend/main/main.c:228
(gdb) 
```
### sql语句：
```
create table xc_sort1_hash(val int, val2 int);
create table  xc_sort2_hash(val int, val2 int);
insert into xc_sort1_hash values (1, 2), (2, 4), (5, 3), (7, 8), (9, 2), (1, 3), (5, 10);
insert into xc_sort2_hash values (1, 2), (2, 4), (5, 3), (7, 8), (9, 2), (1, 3), (5, 10);
select * from xc_sort1_hash join xc_sort2_hash using (val2) order by xc_sort1_hash.val, xc_sort2_hash.val, xc_sort2_hash.val2;
```

**Comment by mass3** [comment]
问题已经解决
postgres=# select * from xc_sort1_hash join xc_sort2_hash using (val2) order by xc_sort1_hash.val, xc_sort2_hash.val, xc_sort2_hash.val2;
 val2 | val | val 
------+-----+-----
    2 |   1 |   1
    3 |   1 |   1
    3 |   1 |   5
    2 |   1 |   9
    4 |   2 |   2
    3 |   5 |   1
    3 |   5 |   5
   10 |   5 |   5
    8 |   7 |   7
    2 |   9 |   1
    2 |   9 |   9
(11 rows)

postgres=#
