### ISSUE TITLE
enable_cluster_plan 开关关闭后，benchmarksql工具压测400并发压测10分钟，datanode 节点产生coredump

### ISSUE THREAD

**Issue by BillyZhu** [ADBSQL/AntDB#62]
测试工具：
```shell
benchmarksql
```
测试集群架构：
```shell 
2C2D，没有设置从节点
```
测试步骤：
```shell
enable_cluster_plan 开关关闭后，benchmarksql工具压测400并发压测10分钟，datanode 节点产生coredump
```
core文件：
```shell
(gdb) bt
#0  0x00007f0feaceb1d7 in raise () from /lib64/libc.so.6
#1  0x00007f0feacec8c8 in abort () from /lib64/libc.so.6
#2  0x0000000000aa6cc8 in ExceptionalCondition (
    conditionName=0xd3ba88 "!(CritSectionCount > 0 || TransactionIdIsCurrentTransactionId(( (!((tup)->t_infomask & 0x0800) && ((tup)->t_infomask & 0x1000) && !((tup)->t_infomask & 0x0080)) ? HeapTupleGetUpdateXid(tup) : ( (tup)-"..., 
    errorType=0xd3b99c "FailedAssertion", fileName=0xd3b960 "/data/gd/build/../adb_sql/src/backend/utils/time/combocid.c", 
    lineNumber=132) at /data/gd/build/../adb_sql/src/backend/utils/error/assert.c:54
#3  0x0000000000aef87e in HeapTupleHeaderGetCmax (tup=0x7f0e99431df8)
    at /data/gd/build/../adb_sql/src/backend/utils/time/combocid.c:131
#4  0x00000000004ddafc in heap_lock_tuple (relation=0x7f0fec94ff10, tuple=0x7ffc5d5ce240, cid=9, mode=LockTupleKeyShare, 
    wait_policy=LockWaitBlock, follow_updates=1 '\001', buffer=0x7ffc5d5ce288, hufd=0x7ffc5d5ce270)
    at /data/gd/build/../adb_sql/src/backend/access/heap/heapam.c:5100
#5  0x00000000006eb3a0 in ExecLockRows (node=0x2e40b60) at /data/gd/build/../adb_sql/src/backend/executor/nodeLockRows.c:179
#6  0x00000000006c7aaf in ExecProcNode (node=0x2e40b60) at /data/gd/build/../adb_sql/src/backend/executor/execProcnode.c:580
#7  0x00000000006c398d in ExecutePlan (estate=0x2e40958, planstate=0x2e40b60, use_parallel_mode=0 '\000', 
    operation=CMD_SELECT, sendTuples=1 '\001', numberTuples=1, direction=ForwardScanDirection, 
    dest=0x1016e20 <spi_printtupDR>) at /data/gd/build/../adb_sql/src/backend/executor/execMain.c:1624
#8  0x00000000006c18d0 in standard_ExecutorRun (queryDesc=0x2e3b6e8, direction=ForwardScanDirection, count=1)
    at /data/gd/build/../adb_sql/src/backend/executor/execMain.c:352
#9  0x00000000006c173f in ExecutorRun (queryDesc=0x2e3b6e8, direction=ForwardScanDirection, count=1)
    at /data/gd/build/../adb_sql/src/backend/executor/execMain.c:297
#10 0x0000000000709394 in _SPI_pquery (queryDesc=0x2e3b6e8, fire_triggers=0 '\000', tcount=1)
    at /data/gd/build/../adb_sql/src/backend/executor/spi.c:2499
#11 0x0000000000708dec in _SPI_execute_plan (plan=0x2e07f88, paramLI=0x2dd55d8, snapshot=0x0, crosscheck_snapshot=0x0, 
    read_only=0 '\000', fire_triggers=0 '\000', tcount=1) at /data/gd/build/../adb_sql/src/backend/executor/spi.c:2272
#12 0x0000000000705b18 in SPI_execute_snapshot (plan=0x2e07f88, Values=0x7ffc5d5ce700, Nulls=0x7ffc5d5ce6c0 "  \\]", 
    snapshot=0x0, crosscheck_snapshot=0x0, read_only=0 '\000', fire_triggers=0 '\000', tcount=1)
    at /data/gd/build/../adb_sql/src/backend/executor/spi.c:536
#13 0x0000000000a201c2 in ri_PerformCheck (riinfo=0x2df1dc8, qkey=0x7ffc5d5cebc0, qplan=0x2e07f88, fk_rel=0x7f0fec8ab150, 
    pk_rel=0x7f0fec94ff10, old_tuple=0x0, new_tuple=0x7ffc5d5cf200, detectNewRows=0 '\000', expect_OK=5)
    at /data/gd/build/../adb_sql/src/backend/utils/adt/ri_triggers.c:3153
#14 0x0000000000a1b10c in RI_FKey_check (trigdata=0x7ffc5d5cf220)
    at /data/gd/build/../adb_sql/src/backend/utils/adt/ri_triggers.c:457
#15 0x0000000000a1b1af in RI_FKey_check_ins (fcinfo=0x7ffc5d5ceda0)
    at /data/gd/build/../adb_sql/src/backend/utils/adt/ri_triggers.c:489
#16 0x000000000069da6b in ExecCallTriggerFunc (trigdata=0x7ffc5d5cf220, tgindx=2, finfo=0x2e11b80, instr=0x0, 
    per_tuple_context=0x2da45b0) at /data/gd/build/../adb_sql/src/backend/commands/trigger.c:1929
#17 0x00000000006a0d5e in AfterTriggerExecute (event=0x2e31950, rel=0x7f0fec8ab150, trigdesc=0x2e117f0, finfo=0x2e11b20, 
    instr=0x0, per_tuple_context=0x2da45b0, trig_tuple_slot1=0x0, trig_tuple_slot2=0x0)
    at /data/gd/build/../adb_sql/src/backend/commands/trigger.c:4040
#18 0x00000000006a11fc in afterTriggerInvokeEvents (events=0x2e01608, firing_id=1, estate=0x2e11588, delete_ok=1 '\001')
    at /data/gd/build/../adb_sql/src/backend/commands/trigger.c:4247
#19 0x00000000006a167e in AfterTriggerEndQuery (estate=0x2e11588)
    at /data/gd/build/../adb_sql/src/backend/commands/trigger.c:4466
#20 0x00000000006c1a7d in standard_ExecutorFinish (queryDesc=0x2dda0b8)
    at /data/gd/build/../adb_sql/src/backend/executor/execMain.c:425
#21 0x00000000006c1974 in ExecutorFinish (queryDesc=0x2dda0b8)
    at /data/gd/build/../adb_sql/src/backend/executor/execMain.c:393
---Type <return> to continue, or q <return> to quit---
#22 0x0000000000945dcf in ProcessQuery (plan=0x2e14e18, 
    sourceText=0x2dd9e08 "INSERT INTO benchmarksql.bmsql_history AS bmsql_history (hist_id, h_c_id, h_c_d_id, h_c_w_id, h_d_id, h_w_id, h_date, h_amount, h_data) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)", params=0x2dd9f20, 
    dest=0x1016da0 <donothingDR>, completionTag=0x7ffc5d5cf690 "INSERT 0 1")
    at /data/gd/build/../adb_sql/src/backend/tcop/pquery.c:237
#23 0x000000000094772e in PortalRunMulti (portal=0x2dbd438, isTopLevel=1 '\001', setHoldSnapshot=0 '\000', 
    dest=0x1016da0 <donothingDR>, altdest=0x1016da0 <donothingDR>, completionTag=0x7ffc5d5cf690 "INSERT 0 1")
    at /data/gd/build/../adb_sql/src/backend/tcop/pquery.c:1408
#24 0x0000000000946c1e in PortalRun (portal=0x2dbd438, count=9223372036854775807, isTopLevel=1 '\001', dest=0x2d89540, 
    altdest=0x2d89540, completionTag=0x7ffc5d5cf690 "INSERT 0 1") at /data/gd/build/../adb_sql/src/backend/tcop/pquery.c:881
#25 0x0000000000941ae5 in exec_execute_message (portal_name=0x2d89128 "", max_rows=9223372036854775807)
    at /data/gd/build/../adb_sql/src/backend/tcop/postgres.c:2458
#26 0x0000000000944b2d in PostgresMain (argc=1, argv=0x2d11100, dbname=0x2d10ff8 "postgres", 
    username=0x2d10fd0 "benchmarksql") at /data/gd/build/../adb_sql/src/backend/tcop/postgres.c:4860
#27 0x00000000008b0123 in BackendRun (port=0x2d06460) at /data/gd/build/../adb_sql/src/backend/postmaster/postmaster.c:4634
#28 0x00000000008af896 in BackendStartup (port=0x2d06460)
    at /data/gd/build/../adb_sql/src/backend/postmaster/postmaster.c:4308
#29 0x00000000008abb71 in ServerLoop () at /data/gd/build/../adb_sql/src/backend/postmaster/postmaster.c:1848
#30 0x00000000008ab19a in PostmasterMain (argc=5, argv=0x2ce3570)
    at /data/gd/build/../adb_sql/src/backend/postmaster/postmaster.c:1456
#31 0x0000000000749aac in main (argc=5, argv=0x2ce3570) at /data/gd/build/../adb_sql/src/backend/main/main.c:228

**Comment by BillyZhu** [comment]
已解决，close issue
