### ISSUE TITLE
打开enable_cluster_plan，插入数据触发rule，hang住，ctrl+C后出现core

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#67]
## 打开enable_cluster_plan ，插入数据触发rule，hang住，ctrl+C后出现core
```
postgres=#  insert into rtest_t4 select a + 1, b from rtest_t9 where a in (20, 30, 40);
^CCancel request sent
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```
### core文件：
```
(gdb) bt
#0  0x000000000072af5b in resetStringInfo (str=0x1c51130) at /home/mass2/git/build/../adb_sql/src/backend/lib/stringinfo.c:72
#1  0x00000000008ce911 in rdc_puterror (port=0x1c50ff0, fmt=0xce9c80 "could set socket to noblocking mode: %m")
    at /home/mass2/git/build/../adb_sql/src/backend/reduce/rdc_comm.c:998
#2  0x00000000008cf6f4 in rdc_set_noblock (port=0x1c50ff0) at /home/mass2/git/build/../adb_sql/src/backend/reduce/rdc_comm.c:1470
#3  0x00000000008cf60c in rdc_getmessage (port=0x1c50ff0, maxlen=0)
    at /home/mass2/git/build/../adb_sql/src/backend/reduce/rdc_comm.c:1402
#4  0x00000000008cab5c in GetReduceListenPort () at /home/mass2/git/build/../adb_sql/src/backend/reduce/adb_reduce.c:290
#5  0x00000000008ca8f6 in StartSelfReduceLauncher (rid=11990) at /home/mass2/git/build/../adb_sql/src/backend/reduce/adb_reduce.c:204
#6  0x000000000071ac25 in StartRemotePlan (msg=0x7ffcd02cd250, rnodes=0x1cac568, context=0x7ffcd02cd240)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execCluster.c:937
#7  0x0000000000718df0 in ExecStartClusterPlan (plan=0x1cabeb0, estate=0x1c97468, eflags=0, rnodes=0x1cac568)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execCluster.c:371
#8  0x0000000000717cba in ExecInitClusterGather (node=0x1cac4d0, estate=0x1c97468, flags=0)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/nodeClusterGather.c:40
#9  0x00000000006d210b in ExecInitNode (node=0x1cac4d0, estate=0x1c97468, eflags=0)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execProcnode.c:359
#10 0x00000000006cd266 in InitPlan (queryDesc=0x1c7d7c8, eflags=0)
---Type <return> to continue, or q <return> to quit--- 
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execMain.c:1000
#11 0x00000000006cc0a3 in standard_ExecutorStart (queryDesc=0x1c7d7c8, eflags=0)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execMain.c:249
#12 0x00000000006cbe82 in ExecutorStart (queryDesc=0x1c7d7c8, eflags=0)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execMain.c:151
#13 0x000000000095ec04 in ProcessQuery (plan=0x1cadf98, 
    sourceText=0x1bef388 "insert into rtest_t4 select a + 1, b from rtest_t9 where a in (20, 30, 40);", params=0x0, dest=0x7f7a056eaa18, 
    completionTag=0x0) at /home/mass2/git/build/../adb_sql/src/backend/tcop/pquery.c:188
#14 0x0000000000960780 in PortalRunMulti (portal=0x1c8f4a8, isTopLevel=1 '\001', setHoldSnapshot=0 '\000', dest=0x7f7a056eaa18, 
    altdest=0x7f7a056eaa18, completionTag=0x7ffcd02cd770 "INSERT 0 3") at /home/mass2/git/build/../adb_sql/src/backend/tcop/pquery.c:1423
#15 0x000000000095fbb5 in PortalRun (portal=0x1c8f4a8, count=9223372036854775807, isTopLevel=1 '\001', dest=0x7f7a056eaa18, 
    altdest=0x7f7a056eaa18, completionTag=0x7ffcd02cd770 "INSERT 0 3") at /home/mass2/git/build/../adb_sql/src/backend/tcop/pquery.c:881
#16 0x0000000000959159 in exec_simple_query (
    query_string=0x1beded8 "insert into rtest_t4 select a + 1, b from rtest_t9 where a in (20, 30, 40);", query_node=0x0)
    at /home/mass2/git/build/../adb_sql/src/backend/tcop/postgres.c:1500
#17 0x000000000095d89e in PostgresMain (argc=1, argv=0x1b8ea20, dbname=0x1b8e880 "postgres", username=0x1b8e860 "mass2")
    at /home/mass2/git/build/../adb_sql/src/backend/tcop/postgres.c:4780
---Type <return> to continue, or q <return> to quit---
#18 0x00000000008c71f8 in BackendRun (port=0x1b8a4e0) at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:4634
#19 0x00000000008c6963 in BackendStartup (port=0x1b8a4e0) at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:4308
#20 0x00000000008c2b53 in ServerLoop () at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:1848
#21 0x00000000008c2201 in PostmasterMain (argc=5, argv=0x1b62610)
    at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:1456
#22 0x0000000000756bd6 in main (argc=5, argv=0x1b62610) at /home/mass2/git/build/../adb_sql/src/backend/main/main.c:228
(gdb) 
```
### 测试sql：
```
set enable_cluster_plan = on;
create table rtest_t4 (a int4, b text);
create table rtest_t5 (a int4, b text);
create table rtest_t6 (a int4, b text);
create table rtest_t7 (a int4, b text);
create table rtest_t8 (a int4, b text);
create table rtest_t9 (a int4, b text);
create rule rtest_t4_ins1 as on insert to rtest_t4
        where new.a >= 10 and new.a < 20 do instead
    insert into rtest_t5 values (new.a, new.b);
create rule rtest_t4_ins2 as on insert to rtest_t4
        where new.a >= 20 and new.a < 30 do
    insert into rtest_t6 values (new.a, new.b);
create rule rtest_t5_ins as on insert to rtest_t5
        where new.a > 15 do
    insert into rtest_t7 values (new.a, new.b);
create rule rtest_t6_ins as on insert to rtest_t6
        where new.a > 25 do instead
    insert into rtest_t8 values (new.a, new.b);
    

insert into rtest_t9 values (1, 'Record should go to rtest_t4');
insert into rtest_t9 values (2, 'Record should go to rtest_t4');
insert into rtest_t9 values (10, 'Record should go to rtest_t5');
insert into rtest_t9 values (15, 'Record should go to rtest_t5');
insert into rtest_t9 values (19, 'Record should go to rtest_t5 and t7');
insert into rtest_t9 values (20, 'Record should go to rtest_t4 and t6');
insert into rtest_t9 values (26, 'Record should go to rtest_t4 and t8');
insert into rtest_t9 values (28, 'Record should go to rtest_t4 and t8');
insert into rtest_t9 values (30, 'Record should go to rtest_t4');
insert into rtest_t9 values (40, 'Record should go to rtest_t4');

insert into rtest_t4 select a + 1, b from rtest_t9 where a in (20, 30, 40);

```
### 版本：
[mass2@localhost1 adb_sql]$ git log
commit dbbb0d890db9c58e59e7206e0c81977976492a74
Author: zhangliang10 <zhangliang10@asiainfo.com>
Date:   Fri Feb 9 15:56:22 2018 +0800

**Comment by constzl** [comment]
commit 3a066c8bbec418613603b4b70354bc80a3c3e23a
Author: zhangliang10 <zhangliang10@asiainfo.com>
Date:   Wed Feb 28 11:06:44 2018 +0800

    修复bug 67：https://github.com/ADBSQL/AntDB/issues/67

**Comment by mass3** [comment]
测试通过
postgres=# insert into rtest_t4 select a + 1, b from rtest_t9 where a in (20, 30, 40);
INSERT 0 3
postgres=#
