### ISSUE TITLE
打开enable_cluster_plan，执行特定语句产生core

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#78]
## 现象：
```
postgres=# set enable_cluster_plan = off;
SET
postgres=# select ten, sum(distinct four) from onek a
postgres-# group by ten
postgres-# having exists (select 1 from onek b where sum(distinct a.four) = b.four) 
postgres-# order by ten;
 ten | sum 
-----+-----
   0 |   2
   2 |   2
   4 |   2
   6 |   2
   8 |   2
(5 rows)

postgres=# set enable_cluster_plan = on;
SET
postgres=# select ten, sum(distinct four) from onek a
postgres-# group by ten
postgres-# having exists (select 1 from onek b where sum(distinct a.four) = b.four) 
postgres-# order by ten;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```

## core文件：
```
(gdb) bt
#0  0x000000000075ea12 in planstate_exec_walk_param (expr=0x0, context=0x7ffd8bf52e70)
    at /home/mass2/git/build/../adb_sql/src/backend/nodes/nodeFuncs.c:3892
#1  0x0000000000759395 in expression_tree_walker (node=0x18b4418, walker=0x75e9fe <planstate_exec_walk_param>, context=0x7ffd8bf52e70)
    at /home/mass2/git/build/../adb_sql/src/backend/nodes/nodeFuncs.c:2047
#2  0x000000000075eafe in planstate_exec_walk_qual (qual=0x18cecd8, context=0x7ffd8bf52e70)
    at /home/mass2/git/build/../adb_sql/src/backend/nodes/nodeFuncs.c:3920
#3  0x000000000075ee1e in planstate_tree_exec_walker (planstate=0x18c79d0, walker=0x71ee2f <DriveClusterReduceWalker>, context=0x0)
    at /home/mass2/git/build/../adb_sql/src/backend/nodes/nodeFuncs.c:4002
#4  0x000000000071ef84 in DriveClusterReduceWalker (node=0x18c79d0)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/nodeClusterReduce.c:1101
#5  0x000000000071f05c in TopDownDriveClusterReduce (node=0x18c79d0)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/nodeClusterReduce.c:1135
#6  0x00000000006d2efd in ExecProcNode (node=0x18c79d0) at /home/mass2/git/build/../adb_sql/src/backend/executor/execProcnode.c:634
#7  0x000000000071bd80 in ExecClusterMergeGather (node=0x18c71b0)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/nodeClusterMergeGather.c:100
#8  0x00000000006d2de5 in ExecProcNode (node=0x18c71b0) at /home/mass2/git/build/../adb_sql/src/backend/executor/execProcnode.c:602
#9  0x00000000006cec05 in ExecutePlan (estate=0x18c0eb8, planstate=0x18c71b0, use_parallel_mode=0 '\000', operation=CMD_SELECT, 
    sendTuples=1 '\001', numberTuples=0, direction=ForwardScanDirection, dest=0x18b5b48)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execMain.c:1624
---Type <return> to continue, or q <return> to quit--- 
#10 0x00000000006cca5d in standard_ExecutorRun (queryDesc=0x185d458, direction=ForwardScanDirection, count=0)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execMain.c:352
#11 0x00000000006cc8bc in ExecutorRun (queryDesc=0x185d458, direction=ForwardScanDirection, count=0)
    at /home/mass2/git/build/../adb_sql/src/backend/executor/execMain.c:297
#12 0x000000000095ea90 in PortalRunSelect (portal=0x18addb8, forward=1 '\001', count=0, dest=0x18b5b48)
    at /home/mass2/git/build/../adb_sql/src/backend/tcop/pquery.c:1040
#13 0x000000000095e683 in PortalRun (portal=0x18addb8, count=9223372036854775807, isTopLevel=1 '\001', dest=0x18b5b48, 
    altdest=0x18b5b48, completionTag=0x7ffd8bf532c0 "") at /home/mass2/git/build/../adb_sql/src/backend/tcop/pquery.c:855
#14 0x0000000000957ced in exec_simple_query (
    query_string=0x17d4d48 "select ten, sum(distinct four) from onek a\ngroup by ten\nhaving exists (select 1 from onek b where sum(distinct a.four) = b.four) \norder by ten;", query_node=0x0) at /home/mass2/git/build/../adb_sql/src/backend/tcop/postgres.c:1501
#15 0x000000000095c3dc in PostgresMain (argc=1, argv=0x17e19c8, dbname=0x17b77c8 "postgres", username=0x17e1830 "mass2")
    at /home/mass2/git/build/../adb_sql/src/backend/tcop/postgres.c:4764
#16 0x00000000008c5e90 in BackendRun (port=0x17dd4b0) at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:4633
#17 0x00000000008c55fb in BackendStartup (port=0x17dd4b0) at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:4307
#18 0x00000000008c17eb in ServerLoop () at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:1847
#19 0x00000000008c0e99 in PostmasterMain (argc=5, argv=0x17b55f0)
    at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:1455
#20 0x000000000075573a in main (argc=5, argv=0x17b55f0) at /home/mass2/git/build/../adb_sql/src/backend/main/main.c:232
```

## 测试sql：
```
CREATE TABLE onek (
    unique1     int4,
    unique2     int4,
    two         int4,
    four        int4,
    ten         int4,
    twenty      int4,
    hundred     int4,
    thousand    int4,
    twothousand int4,
    fivethous   int4,
    tenthous    int4,
    odd         int4,
    even        int4,
    stringu1    name,
    stringu2    name,
    string4     name
);

COPY onek FROM '/home/mass2/regress/data/onek.data';

```

**Comment by mass3** [comment]
回归通过
```
postgres=# set enable_cluster_plan = on;
SET
postgres=# select ten, sum(distinct four) from onek a
postgres-#  group by ten
postgres-#  having exists (select 1 from onek b where sum(distinct a.four) = b.four) 
postgres-#  order by ten;
 ten | sum 
-----+-----
   0 |   2
   2 |   2
   4 |   2
   6 |   2
   8 |   2
(5 rows)
```
