### ISSUE TITLE
执行clean connection出现core

### ISSUE THREAD

**Issue by mass3** [ADBSQL/AntDB#83]
执行clean connection出现core
```
postgres=#  CLEAN CONNECTION to ALL for database postgres to user mass2;
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
ERROR:  Failed to get pooled connections
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```
core文件：
```
(gdb) bt
#0  0x0000000000ad1323 in hash_search (hashp=0x1ae1848, keyPtr=0x7ffd9fe98ac0, action=HASH_ENTER, foundPtr=0x7ffd9fe98aaf "")
    at /home/mass2/git/build/../adb_sql/src/backend/utils/hash/dynahash.c:890
#1  0x000000000074cd6a in agent_acquire_connections (agent=0x1ad9818, msg=0x7ffd9fe98c20)
    at /home/mass2/git/build/../adb_sql/src/backend/pgxc/pool/poolmgr_adb.c:2649
#2  0x0000000000749a34 in agent_handle_input (agent=0x1ad9818, s=0x7ffd9fe98c20)
    at /home/mass2/git/build/../adb_sql/src/backend/pgxc/pool/poolmgr_adb.c:1415
#3  0x0000000000748089 in PoolerLoop () at /home/mass2/git/build/../adb_sql/src/backend/pgxc/pool/poolmgr_adb.c:658
#4  0x00000000007477a6 in PoolManagerInit () at /home/mass2/git/build/../adb_sql/src/backend/pgxc/pool/poolmgr_adb.c:431
#5  0x0000000000569b90 in AuxiliaryProcessMain (argc=2, argv=0x7ffd9fe98ec0)
    at /home/mass2/git/build/../adb_sql/src/backend/bootstrap/bootstrap.c:422
#6  0x00000000008c6cc1 in StartChildProcess (type=PoolerProcess)
    at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:5603
#7  0x00000000008c3d35 in reaper (postgres_signal_arg=17) at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:3047
#8  <signal handler called>
#9  0x000000372ace1603 in __select_nocancel () from /lib64/libc.so.6
#10 0x00000000008c1d86 in ServerLoop () at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:1811
#11 0x00000000008c1565 in PostmasterMain (argc=5, argv=0x1aad5f0)
    at /home/mass2/git/build/../adb_sql/src/backend/postmaster/postmaster.c:1455
#12 0x0000000000755dfa in main (argc=5, argv=0x1aad5f0) at /home/mass2/git/build/../adb_sql/src/backend/main/main.c:232
(gdb) 
```

**Comment by mass3** [comment]
在coordinator上执行语句，功能正确
postgres=# CLEAN CONNECTION to coordinator (coord0) for database cidb to user mass2; 
CLEAN CONNECTION
当有事务未完成时，现象如下：
postgres=# CLEAN CONNECTION to all for database cidb to user mass2; 
ERROR:  Clean connections not completed
force参数测试：
postgres=# CLEAN CONNECTION to all force for database cidb to user mass2; 
CLEAN CONNECTION
指定不同数据库
postgres=# CLEAN CONNECTION to ALL for database postgres to user mass2;
CLEAN CONNECTION
postgres=# CLEAN CONNECTION to ALL for database cidb to user mass2;        
CLEAN CONNECTION
指定node节点：
postgres=# CLEAN CONNECTION to NODE (datanode0) for database cidb to user mass2; 
CLEAN CONNECTION
postgres=# CLEAN CONNECTION to NODE (datanode1) for database cidb to user mass2; 
CLEAN CONNECTION
